included:
  - Source

excluded:
  - Pods

analyzer_rules:

opt_in_rules:
- multiline_arguments
- multiline_function_chains
- multiline_literal_brackets
- multiline_parameters
- multiline_parameters_brackets
- multiline_arguments_brackets
- closing_brace
- closure_end_indentation
- anyobject_protocol
- array_init
- attributes
- block_based_kvo
- closure_parameter_position
- closure_spacing
- colon
- compiler_protocol_init
- convenience_type
- custom_rules
- deployment_target
- discarded_notification_center_observer
- discouraged_direct_init
- duplicate_enum_cases
- duplicate_imports
- dynamic_inline
- empty_count
- empty_enum_arguments
- empty_parameters
- empty_parentheses_with_trailing_closure
- empty_string
- empty_xctest_method
- explicit_enum_raw_value
- explicit_init
- explicit_self
- fallthrough
- first_where
- force_try
- generic_type_name
- identical_operands
- implicit_getter
- implicit_return
- inert_defer
- is_disjoint
- joined_default_parameter
- last_where
- leading_whitespace
- legacy_cggeometry_functions
- legacy_constant
- legacy_constructor
- legacy_hashing
- legacy_multiple
- legacy_nsgeometry_functions
- legacy_random
- let_var_whitespace
- literal_expression_end_indentation
- lower_acl_than_parent     // This can fire off when you type static public instead of public static.  Message is nonsense
- mark
- modifier_order
- nimble_operator
- no_extension_access_modifier
- no_fallthrough_only
- nslocalizedstring_key
- nsobject_prefer_isequal
- operator_usage_whitespace
- operator_whitespace
- overridden_super_call
- prefixed_toplevel_constant
- private_action
- private_outlet
- private_over_fileprivate
- private_unit_test
- prohibited_interface_builder
- prohibited_super_call
- protocol_property_accessors_order
- quick_discouraged_call
- quick_discouraged_focused_test
- quick_discouraged_pending_test
- reduce_boolean
- redundant_discardable_let
- redundant_nil_coalescing
- redundant_objc_attribute
- redundant_optional_initialization
- redundant_set_access_control
- redundant_type_annotation
- redundant_void_return
- required_enum_case
- return_arrow_whitespace
- shorthand_operator
- single_test_class
- sorted_first_last
- sorted_imports
- strict_fileprivate
- strong_iboutlet
- superfluous_disable_command
- switch_case_alignment
- switch_case_on_newline
- syntactic_sugar
- todo
- toggle_bool
- trailing_comma
- trailing_newline
- trailing_semicolon
- unavailable_function
- unneeded_break_in_switch
- unneeded_parentheses_in_closure_argument
- untyped_error_in_catch
- unused_capture_list
- unused_closure_parameter
- unused_control_flow_label
- unused_declaration
- unused_enumerated
- unused_import
- unused_optional_binding
- unused_setter_value
- void_return
- weak_delegate
- xct_specific_matcher
- xctfail_message
- yoda_condition

disabled_rules:

- statement_position
- for_where
- class_delegate_protocol
- closure_body_length
- collection_alignment
- conditional_returns_on_newline
- contains_over_first_not_nil
- control_statement
- comma
- cyclomatic_complexity
- discouraged_object_literal
- discouraged_optional_collection
- discouraged_optional_boolean
- explicit_acl
- explicit_top_level_acl
- explicit_type_interface
- extension_access_modifier
- file_header
- fatal_error_message
- file_length
- file_name
- force_cast
- file_types_order
- force_unwrapping
- function_body_length
- function_default_parameter_at_end
- function_parameter_count
- identifier_name
- implicit_return
- implicitly_unwrapped_optional
- large_tuple
- line_length
- nesting
- missing_docs
- multiple_closures_with_trailing_closure
- no_grouping_extension
- no_space_in_method_call
- notification_center_detachment
- nslocalizedstring_require_bundle
- number_separator
- opening_brace
- object_literal
- override_in_extension
- pattern_matching_keywords
- reduce_into
- redundant_string_enum_value
- required_deinit
- static_operator
- trailing_closure
- type_contents_order
- type_name
- trailing_whitespace
- type_body_length
- unowned_variable_capture
- valid_ibinspectable
- vertical_parameter_alignment
- vertical_parameter_alignment_on_call
- vertical_whitespace_closing_braces
- vertical_whitespace_opening_braces
- vertical_whitespace
- vertical_whitespace_between_cases
